# Generated by Django 2.1 on 2020-04-02 16:31

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200331_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=cloudinary.models.CloudinaryField(default='v1585813006/default.jpg', max_length=255, verbose_name='image'),
        ),
    ]
