# Generated by Django 2.1 on 2020-04-02 23:02

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200402_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=cloudinary.models.CloudinaryField(default='v1585842549/default.jpg', max_length=255, verbose_name='image'),
        ),
    ]
