# Generated by Django 2.1 on 2020-04-21 16:31

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200415_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=cloudinary.models.CloudinaryField(default='v1587364309/defaultNew.png', max_length=255, verbose_name='image'),
        ),
    ]
