# Generated by Django 2.1 on 2020-04-02 16:32

import cloudinary.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgePeople',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='allemail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(default='', max_length=200)),
                ('mail', models.CharField(default='', max_length=200)),
                ('organization', models.CharField(default='', max_length=200)),
                ('places', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realname', models.CharField(default='', max_length=150, verbose_name="<font color='red'>ชื่อจริงและนามสกุล</font>")),
                ('nickname', models.CharField(default='', max_length=50, verbose_name="<font color='red'>ชื่อเล่น</font>")),
                ('realnameEng', models.CharField(blank=True, max_length=150, null=True, verbose_name='ชื่ออังกฤษ')),
                ('age', models.PositiveIntegerField(blank=True, help_text='กรอกอายุ 1- 100 (จำเป็นต้องกรอก)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name="<font color='red'>อายุ(ปี)</font>")),
                ('nationality', models.CharField(default='', max_length=10, verbose_name="<font color='red'>เชื้อชาติ</font>")),
                ('lostday', models.CharField(blank=True, help_text='กรอกวันที่ เช่น 21/01/2530', max_length=10, null=True, verbose_name='วันที่หาย')),
                ('lostTime', models.CharField(blank=True, help_text='กรอกเวลา เช่น 12.00 , 19.30', max_length=5, null=True, verbose_name='เวลาที่หาย')),
                ('lostWhere', models.CharField(blank=True, max_length=100, null=True, verbose_name='สถานที่หาย')),
                ('lostReason', models.CharField(blank=True, max_length=200, null=True, verbose_name='เหตุผลที่หาย')),
                ('identities', models.CharField(default='', help_text='ลักษณะพิเศษ เช่น มีไฝบนหน้า ใส่สร้องทอง ผิวคล้ำเป็นต้น', max_length=100, verbose_name="<font color='red'>ลักษณะพิเศษ</font>")),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='รูปภาพ')),
                ('content', models.TextField(blank=True, help_text='กรอกรายละเอียดเพิ่มเติม', null=True, verbose_name='รายละเอียดเพิ่มเติม')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('gender', models.CharField(default='', max_length=5, verbose_name="<font color='red'>เพศ</font>")),
                ('telephone', models.CharField(default='', max_length=10, verbose_name="<font color='red'>เบอร์โทรติดต่อกับผู้บันทึกข้อมูล</font>")),
                ('email', models.CharField(default='', max_length=100, verbose_name="<font color='red'>อีเมล์ของผู้บันทึกข้อมูล</font>")),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Postfound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realname', models.CharField(default='', max_length=150, verbose_name="<font color='red'>ชื่อจริงและนามสกุล</font>")),
                ('nickname', models.CharField(default='', max_length=50, verbose_name="<font color='red'>ชื่อเล่น</font>")),
                ('realnameEng', models.CharField(blank=True, max_length=150, null=True, verbose_name='ชื่ออังกฤษ')),
                ('age', models.PositiveIntegerField(blank=True, help_text='กรอกอายุ 1- 100', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name="<font color='red'>อายุ(ปี)</font>")),
                ('nationality', models.CharField(default='', max_length=10, verbose_name="<font color='red'>เชื้อชาติ</font>")),
                ('lostday', models.CharField(blank=True, help_text='กรอกวันที่ เช่น 21/01/2530', max_length=10, null=True, verbose_name='วันที่หาย')),
                ('lostTime', models.CharField(blank=True, help_text='กรอกเวลา เช่น 12.00 , 19.30', max_length=5, null=True, verbose_name='เวลาที่หาย')),
                ('lostWhere', models.CharField(blank=True, max_length=100, null=True, verbose_name='สถานที่หาย')),
                ('lostReason', models.CharField(blank=True, max_length=200, null=True, verbose_name='เหตุผลที่หาย')),
                ('identities', models.CharField(default='', help_text='ลักษณะพิเศษ เช่น มีไฝบนหน้า ใส่สร้องทอง ผิวคล้ำเป็นต้น', max_length=100, verbose_name="<font color='red'>ลักษณะพิเศษ</font>")),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='รูปภาพ')),
                ('content', models.TextField(blank=True, help_text='กรอกรายละเอียดเพิ่มเติม', null=True, verbose_name='รายละเอียดเพิ่มเติม')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('gender', models.CharField(default='', max_length=5, verbose_name="<font color='red'>เพศ</font>")),
                ('telephone', models.CharField(default='', max_length=10, verbose_name="<font color='red'>เบอร์โทรติดต่อกับผู้บันทึกข้อมูล</font>")),
                ('email', models.CharField(default='', max_length=100, verbose_name="<font color='red'>อีเมล์ของผู้บันทึกข้อมูล</font>")),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostFree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', help_text='กรอกข้อมูลเช่น พบเจอเด็กหลง , พบเจอคนแก่อยู่ที่ถนน... เป็นต้น', max_length=100, verbose_name="<font color='red'>หัวข้อ</font>")),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='รูปภาพ (สำหรับใส่รูปภาพแกติทั่วไป เช่น รูปเด็กหลงทาง รูปคนแก่หาย เป็นต้น)')),
                ('image2', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='รูปภาพ2 (สำหรับใส่รูปภาพที่รุนแรง ไม่ต้องการเผยรูปนี้ในหน้าโชว์ข้อมูล เช่น รูปเสียชีวิตเป็นต้น)')),
                ('where', models.CharField(default='', help_text='กรอกข้อมูลเช่น พบเจอที่ราชดำเนิน เป็นต้น', max_length=100, verbose_name="<font color='red'>สถานที่พบเจอ</font>")),
                ('content', models.TextField(blank=True, help_text='กรุณากรอกข้อความให้ครบถ้วนเพื่อสิทธิประโยชน์ของท่านและสำหรับผู้แจ้งเบาะแส', null=True, verbose_name='รายละเอียดเพิ่มเติม')),
                ('identities', models.CharField(default='', help_text='ลักษณะพิเศษ เช่น มีไฝบนหน้า ใส่สร้องทอง ผิวคล้ำเป็นต้น', max_length=100, verbose_name="<font color='red'>ลักษณะพิเศษ</font>")),
                ('email', models.CharField(blank=True, help_text='ส่วนของข่อมูลส่วนบุคคล กรอกอีเมล์สำหรับให้ญาติของผู้สูญหายสามารถติดต่อกลับได้', max_length=100, null=True, verbose_name='อีเมล์')),
                ('telephone', models.PositiveIntegerField(blank=True, help_text='ส่วนของข่อมูลส่วนบุคคล กรอกเบอร์โทรศัพท์สำหรับให้ญาติของผู้สูญหายสามารถติดต่อกลับได้', null=True, verbose_name='เบอร์โทรศัพท์ เช่น 0991234567')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('age', models.ManyToManyField(to='blog.AgePeople', verbose_name="<font color='red'>อายุ</font>")),
                ('gender', models.ManyToManyField(to='blog.Gender', verbose_name="<font color='red'>เพศ</font>")),
            ],
        ),
        migrations.CreateModel(
            name='Postmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realname', models.CharField(default='', max_length=150, verbose_name="<font color='red'>ชื่อจริงและนามสกุล</font>")),
                ('nickname', models.CharField(default='', max_length=50, verbose_name="<font color='red'>ชื่อเล่น</font>")),
                ('realnameEng', models.CharField(blank=True, max_length=150, null=True, verbose_name='ชื่ออังกฤษ')),
                ('age', models.PositiveIntegerField(blank=True, help_text='กรอกอายุ 1- 100', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name="<font color='red'>อายุ(ปี)</font>")),
                ('nationality', models.CharField(default='', max_length=10, verbose_name="<font color='red'>เชื้อชาติ</font>")),
                ('lostday', models.CharField(blank=True, help_text='กรอกวันที่ เช่น 21/01/2530', max_length=10, null=True, verbose_name='วันที่หาย')),
                ('lostTime', models.CharField(blank=True, help_text='กรอกเวลา เช่น 12.00 , 19.30', max_length=5, null=True, verbose_name='เวลาที่หาย')),
                ('lostWhere', models.CharField(blank=True, max_length=100, null=True, verbose_name='สถานที่หาย')),
                ('lostReason', models.CharField(blank=True, max_length=200, null=True, verbose_name='เหตุผลที่หาย')),
                ('identities', models.CharField(default='', help_text='ลักษณะพิเศษ เช่น มีไฝบนหน้า ใส่สร้องทอง ผิวคล้ำเป็นต้น', max_length=100, verbose_name="<font color='red'>ลักษณะพิเศษ</font>")),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='รูปภาพ')),
                ('content', models.TextField(blank=True, help_text='กรอกรายละเอียดเพิ่มเติม', null=True, verbose_name='รายละเอียดเพิ่มเติม')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('fromEmail', models.CharField(default='', max_length=150)),
                ('gender', models.CharField(default='', max_length=5, verbose_name="<font color='red'>เพศ</font>")),
                ('author', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostRisk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realname', models.CharField(default='', max_length=150, verbose_name="<font color='red'>ชื่อจริงและนามสกุล</font>")),
                ('nickname', models.CharField(default='', max_length=50, verbose_name="<font color='red'>ชื่อเล่น</font>")),
                ('realnameEng', models.CharField(blank=True, max_length=150, null=True, verbose_name='ชื่ออังกฤษ')),
                ('age', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name="<font color='red'>อายุ</font>")),
                ('nationality', models.CharField(default='', max_length=10, verbose_name="<font color='red'>เชื้อชาติ</font>")),
                ('identities', models.CharField(default='', help_text='ลักษณะพิเศษ เช่น มีไฝบนหน้า ใส่สร้องทอง ผิวคล้ำเป็นต้น', max_length=100, verbose_name="<font color='red'>ลักษณะพิเศษ</font>")),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='รูปภาพ')),
                ('content', models.TextField(blank=True, help_text='กรอกรายละเอียดเพิ่มเติม', null=True, verbose_name='รายละเอียดเพิ่มเติม')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('gender', models.CharField(default='', max_length=5, verbose_name="<font color='red'>เพศ</font>")),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
