# Generated by Django 2.1 on 2020-04-21 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200421_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postfree',
            name='telephone',
            field=models.CharField(blank=True, help_text='ส่วนของข่อมูลส่วนบุคคล กรอกเบอร์โทรสำหรับให้ญาติของผู้สูญหายสามารถติดต่อกลับได้', max_length=10, null=True, verbose_name='เบอร์โทรติดต่อของผู้บันทึกข้อมูล'),
        ),
    ]
