# Generated by Django 2.1 on 2020-04-22 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200421_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postfree',
            name='telephone',
        ),
    ]
