# Generated by Django 2.1 on 2020-03-05 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='allemailtoadmin',
        ),
    ]
